
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'altrix_app') THEN
    CREATE ROLE altrix_app WITH LOGIN PASSWORD '29790f6c861ea7cd47a7624da6e6fef99f0e2df8ae35313f';
  ELSE
    ALTER USER altrix_app WITH PASSWORD '29790f6c861ea7cd47a7624da6e6fef99f0e2df8ae35313f';
  END IF;
END
$$;

GRANT ALL PRIVILEGES ON DATABASE altrix TO altrix_app;
ALTER USER altrix_app BYPASSRLS;
\c altrix
GRANT ALL ON SCHEMA public TO altrix_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO altrix_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO altrix_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO altrix_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO altrix_app;

GRANT USAGE, CREATE ON SCHEMA auth TO altrix_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA auth TO altrix_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA auth TO altrix_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO altrix_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO altrix_app;
