"""
Centralized Enterprise Email Service for AltRix Cloud OS.
Provides:
- Global AltRix Visual Identity & Asset Management (Logo, Brand Mark, Typography, Footers)
- Dynamic Tenant / Institute Identity Injection (Logo, Name, Address, Website)
- Standardized Responsive HTML Email Design System
- Dynamic Variable Resolution (dot-notation & snake_case)
- Central Sender Identity & Event Routing Matrix
- Local VPS Mailu MTA SMTP Dispatch (127.0.0.1:25)
- Token-Safe Audit Delivery Logging
"""
import json
import logging
import smtplib
from datetime import datetime, timezone
from email.message import EmailMessage
from email.utils import formataddr
from typing import Any, Dict, Optional, Tuple
from uuid import uuid4

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger("app.services.email_service")

# Fallback default global branding configuration
DEFAULT_BRANDING = {
    "brand_name": "AltRix",
    "primary_logo_url": "https://altrixcore.com/altrix-logo.png",
    "secondary_logo_url": "https://altrixcore.com/altrix-logo.png",
    "brand_icon_url": "https://altrixcore.com/altrix-icon.png",
    "header_logo_type": "primary",
    "primary_color": "#0f172a",
    "accent_color": "#2563eb",
    "secondary_color": "#64748b",
    "support_email": "support@altrixcore.com",
    "contact_email": "contact@altrixcore.com",
    "website_url": "https://altrixcore.com",
    "footer_text": "Enterprise Identity & Cloud Core Platform",
    "legal_disclaimer": "This email was generated by AltRix Cloud OS on behalf of the registered institution. If you received this in error, please contact security immediately.",
    "social_links": {
        "twitter": "https://twitter.com/altrixcore",
        "linkedin": "https://linkedin.com/company/altrixcore",
    },
}

# Fallback default sender
DEFAULT_SENDER = {
    "key": "security",
    "name": "AltRix Security HQ",
    "email": "security@altrixcore.com",
    "reply_to": "security@altrixcore.com",
}


def build_branded_html_shell(
    branding: Dict[str, Any],
    tenant_info: Dict[str, Any],
    title: str,
    badge_text: str,
    badge_color: str,
    content_html: str,
    cta_text: Optional[str] = None,
    cta_url: Optional[str] = None,
    security_notice: Optional[str] = None,
    border_accent_color: str = "#2563eb",
) -> str:
    """
    Renders an email shell adhering to the AltRix Email Design System.
    Includes hosted AltRix logo & brand icon, optional tenant banner, responsive layout,
    clean CTA buttons, info cards, and compliant email footers.
    """
    logo_url = branding.get("primary_logo_url") or "https://altrixcore.com/altrix-logo.png"
    icon_url = branding.get("brand_icon_url") or "https://altrixcore.com/altrix-icon.png"
    brand_name = branding.get("brand_name") or "AltRix"
    support_email = branding.get("support_email") or "support@altrixcore.com"
    website_url = branding.get("website_url") or "https://altrixcore.com"
    footer_text = branding.get("footer_text") or "Enterprise Identity & Cloud Core Platform"
    legal_disclaimer = branding.get("legal_disclaimer") or ""
    current_year = datetime.now(timezone.utc).year

    # Tenant Header Sub-block if tenant exists
    tenant_header_block = ""
    tenant_name = tenant_info.get("name")
    tenant_logo = tenant_info.get("logo_url")
    if tenant_name:
        if tenant_logo:
            tenant_header_block = f"""
            <div style="display: flex; align-items: center; justify-content: center; gap: 12px; margin-top: 14px; padding-top: 12px; border-top: 1px solid rgba(255,255,255,0.12);">
              <img src="{tenant_logo}" alt="{tenant_name}" style="height: 28px; width: auto; max-width: 120px; object-fit: contain;" />
              <span style="color: #cbd5e1; font-size: 13px; font-weight: 600; letter-spacing: 0.3px;">{tenant_name}</span>
            </div>
            """
        else:
            tenant_header_block = f"""
            <div style="margin-top: 12px; padding-top: 10px; border-top: 1px solid rgba(255,255,255,0.12);">
              <span style="color: #cbd5e1; font-size: 13px; font-weight: 600; letter-spacing: 0.3px;">{tenant_name}</span>
            </div>
            """

    # CTA Button Block
    cta_block = ""
    if cta_text and cta_url:
        cta_block = f"""
        <div style="text-align: center; margin: 32px 0 24px 0;">
          <a href="{cta_url}" target="_blank" style="display: inline-block; background: linear-gradient(135deg, {border_accent_color} 0%, #1d4ed8 100%); color: #ffffff !important; font-size: 15px; font-weight: 700; text-decoration: none; padding: 13px 34px; border-radius: 10px; box-shadow: 0 10px 15px -3px rgba(37, 99, 235, 0.35); letter-spacing: 0.2px;">
            {cta_text} &rarr;
          </a>
        </div>
        """

    # Security Notice Block
    security_block = ""
    if security_notice:
        security_block = f"""
        <div style="font-size: 12px; color: #64748b; background: #f8fafc; padding: 12px 16px; border-radius: 8px; border-left: 3px solid #64748b; margin-top: 24px; line-height: 1.5;">
          <strong>Security Notice:</strong> {security_notice}
        </div>
        """

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  body {{ margin: 0; padding: 0; background-color: #0b1120; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #334155; -webkit-font-smoothing: antialiased; }}
  table {{ border-spacing: 0; border-collapse: collapse; }}
  td {{ padding: 0; }}
  img {{ border: 0; outline: none; text-decoration: none; display: block; }}
  .wrapper {{ width: 100%; table-layout: fixed; background-color: #0b1120; padding: 40px 12px; }}
  .main-card {{ background-color: #ffffff; max-width: 600px; margin: 0 auto; border-radius: 18px; overflow: hidden; box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.45); border: 1px solid #1e293b; }}
  .header {{ background: linear-gradient(145deg, #0f172a 0%, #1e293b 100%); padding: 36px 32px 30px 32px; text-align: center; border-bottom: 3px solid {border_accent_color}; }}
  .content {{ padding: 36px 32px 30px 32px; font-size: 15px; line-height: 1.65; color: #334155; }}
  .badge {{ display: inline-block; background: {badge_color}; font-size: 11px; font-weight: 800; padding: 5px 14px; border-radius: 9999px; text-transform: uppercase; letter-spacing: 0.6px; margin-bottom: 14px; }}
  .title {{ font-size: 22px; font-weight: 800; color: #0f172a; margin: 0 0 14px 0; line-height: 1.3; }}
  .info-box {{ background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 18px; margin: 24px 0; }}
  .footer {{ background-color: #f8fafc; padding: 28px 32px; text-align: center; font-size: 12px; color: #64748b; border-top: 1px solid #e2e8f0; line-height: 1.6; }}
  @media only screen and (max-width: 600px) {{
    .wrapper {{ padding: 16px 8px !important; }}
    .content {{ padding: 24px 20px !important; }}
    .header {{ padding: 24px 20px !important; }}
    .footer {{ padding: 20px 16px !important; }}
  }}
</style>
</head>
<body>
<div class="wrapper">
  <table class="main-card" width="100%" cellpadding="0" cellspacing="0">
    <!-- Brand Header -->
    <tr>
      <td class="header">
        <div style="display: flex; align-items: center; justify-content: center; margin: 0 auto;">
          <img src="{logo_url}" alt="{brand_name}" style="height: 48px; width: auto; max-width: 240px; margin: 0 auto; display: block; filter: drop-shadow(0 2px 4px rgba(0,0,0,0.15));" />
        </div>
        {tenant_header_block}
      </td>
    </tr>
    <!-- Main Content Area -->
    <tr>
      <td class="content">
        <span class="badge">{badge_text}</span>
        <h2 class="title">{title}</h2>
        {content_html}
        {cta_block}
        {security_block}
      </td>
    </tr>
    <!-- Brand Footer -->
    <tr>
      <td class="footer">
        <div style="display: flex; align-items: center; justify-content: center; gap: 8px; margin-bottom: 8px;">
          <img src="{icon_url}" alt="Icon" style="height: 20px; width: 20px; display: inline-block; vertical-align: middle;" />
          <strong style="color: #0f172a; font-size: 13px;">{brand_name} — The AI-Powered Institute Operating System</strong>
        </div>
        <p style="margin: 0 0 6px 0; color: #64748b;">&copy; {current_year} {brand_name} Cloud OS &bull; {footer_text} &bull; All rights reserved.</p>
        <p style="margin: 0 0 8px 0;">
          <a href="{website_url}" style="color: #2563eb; text-decoration: none; font-weight: 600;" target="_blank">Platform Portal</a> &bull; 
          Support: <a href="mailto:{support_email}" style="color: #2563eb; text-decoration: none; font-weight: 600;">{support_email}</a> &bull; 
          <a href="{website_url}/privacy" style="color: #64748b; text-decoration: underline;" target="_blank">Privacy Policy</a> &bull; 
          <a href="{website_url}/terms" style="color: #64748b; text-decoration: underline;" target="_blank">Terms</a>
        </p>
        <p style="margin: 0; font-size: 11px; color: #94a3b8; max-width: 480px; margin: 0 auto; line-height: 1.4;">{legal_disclaimer}</p>
      </td>
    </tr>
  </table>
</div>
</body>
</html>"""


def interpolate_variables(template_str: str, context: Dict[str, Any]) -> str:
    """
    Safely interpolates template placeholders.
    Supports:
    - Dot notation: {{tenant.name}}, {{tenant.logo}}, {{brand.logo}}, {{brand.icon}}, {{user.name}}, {{user.email}}, {{payment.amount}}, etc.
    - Flat notation: {{tenant_name}}, {{activation_link}}, {{reset_link}}, {{name}}, {{email}}, {{role}}, {{expires_in}}, {{support_email}}, {{year}}, etc.
    """
    if not template_str:
        return ""
    result = template_str

    # 1. Flatten dictionary for dot notation support
    flat_map: Dict[str, str] = {}
    for k, v in context.items():
        if isinstance(v, dict):
            for sub_k, sub_v in v.items():
                flat_map[f"{k}.{sub_k}"] = str(sub_v) if sub_v is not None else ""
        else:
            flat_map[k] = str(v) if v is not None else ""

    # 2. Add automatic aliases (e.g. tenant.name -> tenant_name)
    aliases = {
        "tenant_name": flat_map.get("tenant.name", flat_map.get("tenant_name", "")),
        "tenant_logo": flat_map.get("tenant.logo", flat_map.get("tenant_logo", "")),
        "brand_name": flat_map.get("brand.name", flat_map.get("brand_name", "AltRix")),
        "brand_logo": flat_map.get("brand.logo", flat_map.get("brand_logo", "https://altrixcore.com/altrix-logo.png")),
        "brand_icon": flat_map.get("brand.icon", flat_map.get("brand_icon", "https://altrixcore.com/altrix-icon.png")),
        "name": flat_map.get("user.name", flat_map.get("name", "")),
        "email": flat_map.get("user.email", flat_map.get("email", "")),
        "role": flat_map.get("user.role", flat_map.get("role", "")),
    }
    for ak, av in aliases.items():
        if ak not in flat_map and av:
            flat_map[ak] = av

    # 3. Perform string replacement
    for key, val in flat_map.items():
        placeholder = f"{{{{{key}}}}}"
        result = result.replace(placeholder, val)

    return result


class CentralEmailService:
    """
    Unified AltRix Enterprise Email Service.
    Resolves branding, tenant details, sender identities, and templates from PostgreSQL,
    renders responsive HTML email, and dispatches via local Mailu VPS SMTP (127.0.0.1:25).
    """

    @staticmethod
    async def get_branding(db: AsyncSession) -> Dict[str, Any]:
        """Fetch global email branding configuration with safe defaults."""
        branding = dict(DEFAULT_BRANDING)
        try:
            res = await db.execute(
                text("""
                    SELECT brand_name, primary_logo_url, secondary_logo_url, brand_icon_url,
                           header_logo_type, primary_color, accent_color, secondary_color,
                           support_email, contact_email, website_url, footer_text, legal_disclaimer, social_links
                    FROM public.email_branding_config
                    WHERE is_active = TRUE
                    ORDER BY updated_at DESC
                    LIMIT 1
                """)
            )
            row = res.fetchone()
            if row:
                branding.update({
                    "brand_name": row.brand_name or DEFAULT_BRANDING["brand_name"],
                    "primary_logo_url": row.primary_logo_url or DEFAULT_BRANDING["primary_logo_url"],
                    "secondary_logo_url": row.secondary_logo_url or DEFAULT_BRANDING["secondary_logo_url"],
                    "brand_icon_url": row.brand_icon_url or DEFAULT_BRANDING["brand_icon_url"],
                    "header_logo_type": row.header_logo_type or DEFAULT_BRANDING["header_logo_type"],
                    "primary_color": row.primary_color or DEFAULT_BRANDING["primary_color"],
                    "accent_color": row.accent_color or DEFAULT_BRANDING["accent_color"],
                    "secondary_color": row.secondary_color or DEFAULT_BRANDING["secondary_color"],
                    "support_email": row.support_email or DEFAULT_BRANDING["support_email"],
                    "contact_email": row.contact_email or DEFAULT_BRANDING["contact_email"],
                    "website_url": row.website_url or DEFAULT_BRANDING["website_url"],
                    "footer_text": row.footer_text or DEFAULT_BRANDING["footer_text"],
                    "legal_disclaimer": row.legal_disclaimer or DEFAULT_BRANDING["legal_disclaimer"],
                })
        except Exception as e:
            logger.warning(f"Failed to fetch email_branding_config: {e}. Using defaults.")
        return branding

    @staticmethod
    async def resolve_tenant_branding(school_id: Optional[Any], db: AsyncSession) -> Dict[str, Any]:
        """Resolve tenant name, logo, contact, website server-side."""
        tenant_info = {"name": "", "logo_url": "", "website": "", "address": "", "support_email": ""}
        if not school_id:
            return tenant_info

        try:
            import uuid
            sid = uuid.UUID(str(school_id)) if not isinstance(school_id, uuid.UUID) else school_id
            res_s = await db.execute(
                text("SELECT name, slug, address, phone, email FROM public.schools WHERE id = :sid LIMIT 1"),
                {"sid": sid},
            )
            row_s = res_s.fetchone()
            if row_s:
                tenant_info["name"] = row_s.name or ""
                tenant_info["address"] = row_s.address or ""
                tenant_info["support_email"] = row_s.email or ""

            # Check school_branding for logo_url
            res_b = await db.execute(
                text("SELECT logo_url, website FROM public.school_branding WHERE school_id = :sid LIMIT 1"),
                {"sid": sid},
            )
            row_b = res_b.fetchone()
            if row_b:
                tenant_info["logo_url"] = row_b.logo_url or ""
                tenant_info["website"] = row_b.website or ""
        except Exception as e:
            logger.warning(f"Error resolving tenant branding for school {school_id}: {e}")

        return tenant_info

    @staticmethod
    async def resolve_event(
        event_name: str,
        db: AsyncSession,
    ) -> Tuple[Dict[str, Any], Dict[str, Any]]:
        """Resolves (sender_identity, template) mapped to event_name."""
        sender_identity = dict(DEFAULT_SENDER)
        template_data = {
            "key": event_name,
            "subject": f"AltRix Notification: {event_name.replace('_', ' ').title()}",
            "html": "<p>AltRix System Notification</p>",
            "text": "AltRix System Notification",
            "cta_text": None,
            "cta_url_variable": None,
        }

        try:
            res_map = await db.execute(
                text("""
                    SELECT m.sender_identity_key, m.template_key,
                           s.name as sender_name, s.email as sender_email, s.reply_to,
                           t.subject, t.html_content, t.text_content, t.cta_text, t.cta_url_variable
                    FROM public.email_event_mappings m
                    LEFT JOIN public.email_sender_identities s ON m.sender_identity_key = s.key
                    LEFT JOIN public.email_templates t ON m.template_key = t.key
                    WHERE m.event_name = :event_name AND (s.is_active = TRUE OR s.is_active IS NULL) AND (t.is_active = TRUE OR t.is_active IS NULL)
                    LIMIT 1
                """),
                {"event_name": event_name},
            )
            row = res_map.fetchone()
            if row:
                if row.sender_email:
                    sender_identity = {
                        "key": row.sender_identity_key,
                        "name": row.sender_name or DEFAULT_SENDER["name"],
                        "email": row.sender_email,
                        "reply_to": row.reply_to,
                    }
                if row.html_content:
                    template_data = {
                        "key": row.template_key,
                        "subject": row.subject,
                        "html": row.html_content,
                        "text": row.text_content or "",
                        "cta_text": row.cta_text,
                        "cta_url_variable": row.cta_url_variable,
                    }
            else:
                # Fallback to direct template lookup by key
                res_tmpl = await db.execute(
                    text("""
                        SELECT t.key, t.subject, t.html_content, t.text_content, t.sender_identity_key, t.cta_text, t.cta_url_variable,
                               s.name as sender_name, s.email as sender_email, s.reply_to
                        FROM public.email_templates t
                        LEFT JOIN public.email_sender_identities s ON t.sender_identity_key = s.key
                        WHERE t.key = :event_name AND t.is_active = TRUE
                        LIMIT 1
                    """),
                    {"event_name": event_name},
                )
                row_t = res_tmpl.fetchone()
                if row_t:
                    template_data = {
                        "key": row_t.key,
                        "subject": row_t.subject,
                        "html": row_t.html_content,
                        "text": row_t.text_content or "",
                        "cta_text": row_t.cta_text,
                        "cta_url_variable": row_t.cta_url_variable,
                    }
                    if row_t.sender_email:
                        sender_identity = {
                            "key": row_t.sender_identity_key or "security",
                            "name": row_t.sender_name or "AltRix Security HQ",
                            "email": row_t.sender_email,
                            "reply_to": row_t.reply_to,
                        }
        except Exception as e:
            logger.warning(f"Error resolving email event mapping for '{event_name}': {e}")

        return sender_identity, template_data

    @staticmethod
    async def send_event(
        event_name: str,
        recipient: str,
        context: Dict[str, Any],
        db: AsyncSession,
        school_id: Optional[Any] = None,
        override_sender_key: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Primary transactional email dispatcher.
        Resolves global branding, tenant information, sender identity, and template.
        Dispatches via local Mailu VPS SMTP (127.0.0.1:25) and records audit logs.
        """
        branding = await CentralEmailService.get_branding(db)
        tenant_info = await CentralEmailService.resolve_tenant_branding(school_id, db)

        # Merge context with global branding and tenant defaults
        ctx = dict(context)
        ctx.setdefault("year", datetime.now(timezone.utc).year)
        ctx.setdefault("email", recipient)
        ctx.setdefault("support_email", branding.get("support_email", "support@altrixcore.com"))
        ctx.setdefault("contact_email", branding.get("contact_email", "contact@altrixcore.com"))
        ctx.setdefault("website_url", branding.get("website_url", "https://altrixcore.com"))
        ctx["brand"] = {
            "name": branding.get("brand_name", "AltRix"),
            "logo": branding.get("primary_logo_url", "https://altrixcore.com/altrix-logo.png"),
            "icon": branding.get("brand_icon_url", "https://altrixcore.com/altrix-icon.png"),
            "support_email": branding.get("support_email", "support@altrixcore.com"),
            "website": branding.get("website_url", "https://altrixcore.com"),
        }
        ctx["tenant"] = {
            "name": tenant_info.get("name") or ctx.get("tenant_name", "AltRix Institute"),
            "logo": tenant_info.get("logo_url") or ctx.get("tenant_logo", ""),
            "website": tenant_info.get("website") or "",
            "address": tenant_info.get("address") or "",
        }
        ctx.setdefault("tenant_name", ctx["tenant"]["name"])
        ctx.setdefault("tenant_logo", ctx["tenant"]["logo"])

        sender, template = await CentralEmailService.resolve_event(event_name, db)

        # Apply override sender if explicitly specified
        if override_sender_key:
            try:
                res_s = await db.execute(
                    text("SELECT name, email, reply_to FROM public.email_sender_identities WHERE key = :key LIMIT 1"),
                    {"key": override_sender_key}
                )
                row_s = res_s.fetchone()
                if row_s:
                    sender = {
                        "key": override_sender_key,
                        "name": row_s.name,
                        "email": row_s.email,
                        "reply_to": row_s.reply_to,
                    }
            except Exception as e:
                logger.warning(f"Failed to load override sender {override_sender_key}: {e}")

        # Render variables
        subject_rendered = interpolate_variables(template.get("subject", "AltRix Notification"), ctx)
        html_rendered = interpolate_variables(template.get("html", "<p>AltRix Notification</p>"), ctx)
        text_rendered = interpolate_variables(template.get("text", "AltRix Notification"), ctx)

        # Construct EmailMessage
        msg = EmailMessage()
        msg["Subject"] = subject_rendered
        msg["From"] = formataddr((sender["name"], sender["email"]))
        msg["To"] = recipient
        if sender.get("reply_to"):
            msg["Reply-To"] = sender["reply_to"]

        if text_rendered:
            msg.set_content(text_rendered)
        else:
            msg.set_content("Please view this email in an HTML-compatible client.")

        msg.add_alternative(html_rendered, subtype="html")

        # Generate Message-ID
        message_id = f"{uuid4()}@altrixcore.com"
        msg["Message-ID"] = f"<{message_id}>"

        status = "sent"
        error_details = None

        # Dispatch via Mailu Local SMTP (127.0.0.1:25)
        try:
            with smtplib.SMTP("127.0.0.1", 25, timeout=10) as server:
                server.send_message(msg)
            logger.info(f"Dispatched '{event_name}' email to {recipient} via {sender['email']}")
        except Exception as smtp_err:
            status = "failed"
            error_details = str(smtp_err)
            logger.error(f"SMTP error sending '{event_name}' to {recipient}: {smtp_err}")

        # Record delivery log (safe without sensitive tokens)
        try:
            await db.execute(
                text("""
                    INSERT INTO public.email_logs (
                        recipient_email, sender_email, sender_name, event_name, template_key, subject, status, error_details, message_id, sent_at, metadata
                    ) VALUES (
                        :recipient, :sender_email, :sender_name, :event_name, :template_key, :subject, :status, :error_details, :message_id, NOW(), :meta
                    )
                """),
                {
                    "recipient": recipient,
                    "sender_email": sender["email"],
                    "sender_name": sender["name"],
                    "event_name": event_name,
                    "template_key": template.get("key", event_name),
                    "subject": subject_rendered,
                    "status": status,
                    "error_details": error_details,
                    "message_id": message_id,
                    "meta": json.dumps({"event": event_name, "role": ctx.get("role"), "tenant": ctx["tenant"]["name"]}),
                },
            )
            await db.commit()
        except Exception as log_err:
            logger.warning(f"Failed to record email delivery log: {log_err}")

        return {
            "ok": status == "sent",
            "status": status,
            "message_id": message_id,
            "recipient": recipient,
            "sender": sender["email"],
            "error": error_details,
        }

    @staticmethod
    async def send_raw_test(
        sender_email: str,
        sender_name: str,
        recipient: str,
        subject: str,
        html_content: str,
        text_content: Optional[str],
        db: AsyncSession,
    ) -> Dict[str, Any]:
        """Sends an immediate test email from Super Master Admin Test Lab."""
        msg = EmailMessage()
        msg["Subject"] = f"[TEST] {subject}"
        msg["From"] = formataddr((sender_name, sender_email))
        msg["To"] = recipient
        msg["X-AltRix-Test"] = "true"

        if text_content:
            msg.set_content(text_content)
        else:
            msg.set_content("This is an AltRix test email dispatch.")

        msg.add_alternative(html_content, subtype="html")

        status = "sent"
        error_details = None
        message_id = f"test-{uuid4()}@altrixcore.com"
        msg["Message-ID"] = f"<{message_id}>"

        try:
            with smtplib.SMTP("127.0.0.1", 25, timeout=10) as server:
                server.send_message(msg)
            logger.info(f"Dispatched TEST email to {recipient} from {sender_email}")
        except Exception as err:
            status = "failed"
            error_details = str(err)
            logger.error(f"Failed to send test email to {recipient}: {err}")

        try:
            await db.execute(
                text("""
                    INSERT INTO public.email_logs (
                        recipient_email, sender_email, sender_name, event_name, template_key, subject, status, error_details, message_id, sent_at, metadata
                    ) VALUES (
                        :recipient, :sender_email, :sender_name, 'test_dispatch', 'custom_test', :subject, :status, :error_details, :message_id, NOW(), '{"is_test": true}'::jsonb
                    )
                """),
                {
                    "recipient": recipient,
                    "sender_email": sender_email,
                    "sender_name": sender_name,
                    "subject": f"[TEST] {subject}",
                    "status": status,
                    "error_details": error_details,
                    "message_id": message_id,
                },
            )
            await db.commit()
        except Exception as log_err:
            logger.warning(f"Failed to record test email log: {log_err}")

        return {
            "ok": status == "sent",
            "status": status,
            "message_id": message_id,
            "recipient": recipient,
            "sender": sender_email,
            "error": error_details,
        }
