import { useState, useEffect, useCallback } from "react";
import { supabase, USE_FASTAPI } from "@/integrations/supabase/client";
import { apiClient } from "@/lib/api-client";
import { toast } from "sonner";

// Static production fallback VAPID Public Key to ensure out-of-the-box setup
const DEFAULT_VAPID_PUBLIC_KEY = "BNG7tMXxDXwlo-9asSen2ow4QAaSpEj5bvR1qTzFZWJd_MaPAm8QjcQlf-q2wMiEeUZn05oVH_6cVjSLEQtoado";

function urlBase64ToUint8Array(base64String: string) {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

export function useWebPush() {
  const [isSupported, setIsSupported] = useState(false);
  const [permission, setPermission] = useState<NotificationPermission>("default");
  const [isSubscribed, setIsSubscribed] = useState(false);
  const [loading, setLoading] = useState(true);

  // Check support and active subscription status
  useEffect(() => {
    if (typeof window === "undefined") return;

    const checkSupport = async () => {
      const supported = 'serviceWorker' in navigator && 'PushManager' in window && 'Notification' in window;
      setIsSupported(supported);
      if (!supported) {
        setLoading(false);
        return;
      }

      setPermission(Notification.permission);

      try {
        const registration = await navigator.serviceWorker.ready;
        const subscription = await registration.pushManager.getSubscription();
        setIsSubscribed(!!subscription);
      } catch (e) {
        console.error("Error checking push subscription:", e);
      } finally {
        setLoading(false);
      }
    };

    void checkSupport();
  }, []);

  const subscribe = useCallback(async () => {
    if (!isSupported) {
      toast.error("Push notifications are not supported on this browser.");
      return false;
    }

    setLoading(true);
    try {
      // 1. Request permissions if default
      const perm = await Notification.requestPermission();
      setPermission(perm);
      if (perm !== "granted") {
        toast.error("Notification permission denied.");
        setLoading(false);
        return false;
      }

      // 2. Fetch VAPID public key
      let publicKey = "";
      if (USE_FASTAPI) {
        try {
          const res = await apiClient.get("/notifications/push/public-key");
          publicKey = res.data.public_key;
        } catch (apiErr) {
          console.warn("Failed to fetch public key from FastAPI, falling back to env/database:", apiErr);
        }
      }

      if (!publicKey) {
        try {
          // Supabase Fallback: query from system_settings table
          const { data, error } = await supabase
            .from("system_settings")
            .select("value")
            .eq("key", "vapid_public_key")
            .single();
          
          if (!error && data) {
            publicKey = data.value;
          }
        } catch (dbErr) {
          console.warn("Failed to query VAPID public key from Supabase DB:", dbErr);
        }
      }

      // If still empty, use default static fallback VAPID key
      if (!publicKey) {
        publicKey = (import.meta.env.VITE_VAPID_PUBLIC_KEY as string) || DEFAULT_VAPID_PUBLIC_KEY;
      }

      if (!publicKey) {
        throw new Error("VAPID public key not found. Make sure backend is active or VITE_VAPID_PUBLIC_KEY is configured.");
      }

      // 3. Register sw.js if not registered yet
      const registration = await navigator.serviceWorker.register("/sw.js", {
        scope: "/"
      });
      await navigator.serviceWorker.ready;

      // 4. Subscribe browser PushManager
      const convertedKey = urlBase64ToUint8Array(publicKey);
      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: convertedKey
      });

      // 5. Send registration payload to backend or Supabase
      const rawSub = subscription.toJSON();
      if (!rawSub.endpoint || !rawSub.keys?.p256dh || !rawSub.keys?.auth) {
        throw new Error("Malformed subscription object generated by browser.");
      }

      if (USE_FASTAPI) {
        await apiClient.post("/notifications/push/subscribe", {
          endpoint: rawSub.endpoint,
          p256dh: rawSub.keys.p256dh,
          auth: rawSub.keys.auth,
          device_info: navigator.userAgent
        });
      } else {
        // Supabase Fallback
        const { data: sessionData } = await supabase.auth.getSession();
        const user = sessionData?.session?.user;
        if (!user) throw new Error("No authenticated user session");

        const { error } = await supabase
          .from("user_web_push_subscriptions")
          .upsert({
            user_id: user.id,
            endpoint: rawSub.endpoint,
            p256dh: rawSub.keys.p256dh,
            auth: rawSub.keys.auth,
            device_info: navigator.userAgent
          }, { onConflict: "endpoint" });
        if (error) throw error;
      }

      setIsSubscribed(true);
      toast.success("Successfully subscribed to PWA Push Notifications!");
      return true;
    } catch (e: any) {
      console.error("Push subscription failed:", e);
      toast.error(e?.message || "Failed to enable push notifications.");
      return false;
    } finally {
      setLoading(false);
    }
  }, [isSupported]);

  const unsubscribe = useCallback(async () => {
    if (!isSupported) return false;

    setLoading(true);
    try {
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      if (subscription) {
        const endpoint = subscription.endpoint;
        
        // Remove on backend or Supabase
        if (USE_FASTAPI) {
          await apiClient.post("/notifications/push/unsubscribe", { endpoint });
        } else {
          // Supabase Fallback
          const { error } = await supabase
            .from("user_web_push_subscriptions")
            .delete()
            .eq("endpoint", endpoint);
          if (error) throw error;
        }
        
        // Remove on browser
        await subscription.unsubscribe();
      }
      setIsSubscribed(false);
      toast.success("Unsubscribed from push notifications.");
      return true;
    } catch (e: any) {
      console.error("Push unsubscription failed:", e);
      toast.error("Failed to disable push notifications.");
      return false;
    } finally {
      setLoading(false);
    }
  }, [isSupported]);

  return {
    isSupported,
    permission,
    isSubscribed,
    loading,
    subscribe,
    unsubscribe
  };
}
