-- Custom OTP codes table for password reset flow (bypasses Supabase SMTP)
-- OTPs are generated by the send-otp edge function and verified client-side.

create table if not exists public.custom_otp_codes (
  id          uuid primary key default gen_random_uuid(),
  email_hash  text not null,
  code_hash   text not null,         -- SHA-256 of the 6-digit code
  purpose     text not null default 'password_reset',
  expires_at  timestamptz not null default (now() + interval '10 minutes'),
  used        boolean not null default false,
  created_at  timestamptz not null default now()
);

-- Index for fast lookup by email_hash
create index if not exists custom_otp_codes_email_hash_idx
  on public.custom_otp_codes (email_hash, expires_at)
  where used = false;

-- Auto-cleanup: delete expired/used codes older than 1 hour
create or replace function public.cleanup_expired_otps()
returns void language sql security definer as $$
  delete from public.custom_otp_codes
  where expires_at < now() - interval '1 hour' or used = true;
$$;

-- RLS: edge functions use service_role, no client access needed
alter table public.custom_otp_codes enable row level security;

-- No public select/insert/update — only service_role (edge functions) can access
