-- =========================================================================
-- AltRix Migration: Professional Email Branding & Template Management System
-- Schema: email_branding_config, email_assets, email_sender_identities,
--         email_templates, email_template_versions, email_event_mappings, email_logs
-- =========================================================================

-- 1. Table: email_branding_config (Global System-Level Email Branding)
CREATE TABLE IF NOT EXISTS public.email_branding_config (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    brand_name VARCHAR(128) NOT NULL DEFAULT 'AltRix',
    primary_logo_url VARCHAR(512) NOT NULL DEFAULT 'https://altrixcore.com/altrix-logo.png',
    secondary_logo_url VARCHAR(512),
    brand_icon_url VARCHAR(512) NOT NULL DEFAULT 'https://altrixcore.com/altrix-icon.png',
    header_logo_type VARCHAR(32) NOT NULL DEFAULT 'primary', -- primary, secondary, icon_text
    primary_color VARCHAR(32) NOT NULL DEFAULT '#0f172a',
    accent_color VARCHAR(32) NOT NULL DEFAULT '#2563eb',
    secondary_color VARCHAR(32) NOT NULL DEFAULT '#64748b',
    support_email VARCHAR(255) NOT NULL DEFAULT 'support@altrixcore.com',
    contact_email VARCHAR(255) NOT NULL DEFAULT 'contact@altrixcore.com',
    website_url VARCHAR(512) NOT NULL DEFAULT 'https://altrixcore.com',
    footer_text TEXT NOT NULL DEFAULT 'Enterprise Identity & Cloud Core Platform',
    legal_disclaimer TEXT DEFAULT 'This email was generated by AltRix Cloud OS on behalf of the registered institution. If you received this in error, please contact security immediately.',
    social_links JSONB DEFAULT '{"twitter": "https://twitter.com/altrixcore", "linkedin": "https://linkedin.com/company/altrixcore"}'::jsonb,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Seed default global branding record if none exists
INSERT INTO public.email_branding_config (
    brand_name, primary_logo_url, brand_icon_url, header_logo_type,
    primary_color, accent_color, secondary_color,
    support_email, contact_email, website_url, footer_text, legal_disclaimer
)
SELECT
    'AltRix',
    'https://altrixcore.com/altrix-logo.png',
    'https://altrixcore.com/altrix-icon.png',
    'primary',
    '#0f172a',
    '#2563eb',
    '#64748b',
    'support@altrixcore.com',
    'contact@altrixcore.com',
    'https://altrixcore.com',
    'Enterprise Identity & Cloud Core Platform',
    'This email was generated by AltRix Cloud OS on behalf of the registered institution. If you received this in error, please contact security immediately.'
WHERE NOT EXISTS (SELECT 1 FROM public.email_branding_config LIMIT 1);

-- 2. Table: email_assets (Managed Brand Assets for Email Rendering)
CREATE TABLE IF NOT EXISTS public.email_assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(128) NOT NULL,
    asset_type VARCHAR(64) NOT NULL, -- primary_logo, secondary_logo, brand_icon, header_logo, footer_logo, custom_badge
    url VARCHAR(512) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(64) DEFAULT 'image/png',
    file_size_bytes INT DEFAULT 0,
    dimensions VARCHAR(64), -- e.g. '512x140'
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_email_assets_type ON public.email_assets(asset_type);

-- Seed default assets
INSERT INTO public.email_assets (name, asset_type, url, filename, dimensions)
VALUES
    ('AltRix Official Primary Logo', 'primary_logo', 'https://altrixcore.com/altrix-logo.png', 'altrix-logo.png', '512x140'),
    ('AltRix Official Brand Icon', 'brand_icon', 'https://altrixcore.com/altrix-icon.png', 'altrix-icon.png', '128x128')
ON CONFLICT DO NOTHING;

-- 3. Table: email_sender_identities (Central Senders on mail.altrixcore.com)
CREATE TABLE IF NOT EXISTS public.email_sender_identities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    key VARCHAR(64) UNIQUE NOT NULL,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(255) NOT NULL,
    reply_to VARCHAR(255),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_email_senders_key ON public.email_sender_identities(key);

-- Seed comprehensive sender identities
INSERT INTO public.email_sender_identities (key, name, email, reply_to, is_default, is_active)
VALUES
    ('security', 'AltRix Security HQ', 'security@altrixcore.com', 'security@altrixcore.com', FALSE, TRUE),
    ('no_reply', 'AltRix Platform System', 'no-reply@altrixcore.com', NULL, TRUE, TRUE),
    ('support', 'AltRix Customer Support', 'support@altrixcore.com', 'support@altrixcore.com', FALSE, TRUE),
    ('info', 'AltRix Information Desk', 'info@altrixcore.com', 'info@altrixcore.com', FALSE, TRUE),
    ('ceo', 'AltRix Executive Office', 'ceo@altrixcore.com', 'ceo@altrixcore.com', FALSE, TRUE),
    ('notifications', 'AltRix Cloud Notifications', 'notifications@altrixcore.com', 'no-reply@altrixcore.com', FALSE, TRUE),
    ('contact', 'AltRix Direct Contact', 'contact@altrixcore.com', 'contact@altrixcore.com', FALSE, TRUE),
    ('billing', 'AltRix Billing & Finance', 'billing@altrixcore.com', 'billing@altrixcore.com', FALSE, TRUE),
    ('system', 'AltRix System Engine', 'system@altrixcore.com', NULL, FALSE, TRUE)
ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    email = EXCLUDED.email,
    reply_to = EXCLUDED.reply_to,
    updated_at = NOW();

-- 4. Table: email_templates
CREATE TABLE IF NOT EXISTS public.email_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    key VARCHAR(64) UNIQUE NOT NULL,
    name VARCHAR(128) NOT NULL,
    category VARCHAR(64) NOT NULL, -- Authentication, Staff/HR, Finance, Academic, Communication, System
    subject VARCHAR(255) NOT NULL,
    sender_identity_key VARCHAR(64) REFERENCES public.email_sender_identities(key) ON UPDATE CASCADE ON DELETE SET NULL,
    html_content TEXT NOT NULL,
    text_content TEXT,
    cta_text VARCHAR(128),
    cta_url_variable VARCHAR(128),
    available_variables JSONB DEFAULT '[]'::jsonb,
    version INT NOT NULL DEFAULT 1,
    is_system BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_email_templates_key ON public.email_templates(key);
CREATE INDEX IF NOT EXISTS idx_email_templates_category ON public.email_templates(category);

-- 5. Table: email_template_versions (Version History & Rollback)
CREATE TABLE IF NOT EXISTS public.email_template_versions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    template_key VARCHAR(64) NOT NULL REFERENCES public.email_templates(key) ON DELETE CASCADE,
    version INT NOT NULL,
    subject VARCHAR(255) NOT NULL,
    html_content TEXT NOT NULL,
    text_content TEXT,
    created_by_user_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_email_tmpl_versions_key ON public.email_template_versions(template_key, version DESC);

-- 6. Table: email_event_mappings
CREATE TABLE IF NOT EXISTS public.email_event_mappings (
    event_name VARCHAR(64) PRIMARY KEY,
    sender_identity_key VARCHAR(64) NOT NULL REFERENCES public.email_sender_identities(key) ON UPDATE CASCADE,
    template_key VARCHAR(64) NOT NULL REFERENCES public.email_templates(key) ON UPDATE CASCADE,
    description VARCHAR(255),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. Table: email_logs
CREATE TABLE IF NOT EXISTS public.email_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    recipient_email VARCHAR(255) NOT NULL,
    sender_email VARCHAR(255) NOT NULL,
    sender_name VARCHAR(128),
    event_name VARCHAR(64) NOT NULL,
    template_key VARCHAR(64),
    subject VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL, -- sent, failed, delivered, bounced
    error_details TEXT,
    message_id VARCHAR(255),
    sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_email_logs_recipient ON public.email_logs(LOWER(recipient_email));
CREATE INDEX IF NOT EXISTS idx_email_logs_event_name ON public.email_logs(event_name);
CREATE INDEX IF NOT EXISTS idx_email_logs_sent_at ON public.email_logs(sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_logs_status ON public.email_logs(status);
